#  This Source Code Form is subject to the terms of the Mozilla Public
#License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

game:
  max_players: 16
  min_players: 2
  
topics:
  - Red Bricks
  - Red Firetruck
  - Rocket
  - Airplane
  - Minecraft
  - Camera
  - Computer
  - Laptop
  - Justice
  - Space
  - Zoo
  - Bear
  - Video Game
  - Flower
  - Mob
  - Pirates
  - Boat
  - Time
  - Family
  - Chair
  - Breakfast
  - Fruit
  - Table
  - Calculator
  - Mouse
  - House
  - Bunny
  - Magic
  - Disney
  - Cup
  - Soda
  - Drink
  - Roo Roo (Dog)
  - Cat
  - Pig
  - Cow
  - Hairbrush
  - Sponge
  - Sink
  - Soap
  - Towel
  - Fish
  - Fish Tank
  - Blaze
  - Chicken
  - Tree
  - Park
  - Library
  - City Hall
  - Harp
  - Drum
  - Piano
  - Guitar
  - Music
  - Television
  - Book
  - Superhero
  - Bacon and Eggs
  - Footware
  - Clothes
  - Camping
  - Internet
  - Emoji
  - EpicRealm
  - Money
  - Bank
  - Lightbulb
  - Ladder
  - Train
  - Car
  - Truck
  - Crane  