name: EpicRandomBuilders
version: 0.2.1-ALPHA
authors: [JustBru00, Justin Brubaker]
main: com.gmail.justbru00.epic.randombuilders.main.Main
api-version: 1.15

commands:
  game:
    description: Preforms game functions.
  map:
    description: Preforms map functions.
  spec:
    description: Changes you to a spectator.  
  testloc:
    description: Tests the locations. 
  settime:
    description: Sets the time  
  lobby:
    description: Lobby command     
  hub:
    description: Lobby command      